services:
  - type: worker
    name: anime-bot-telegram
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r bot/requirements.txt
    startCommand: cd bot && python anime_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: TON_WALLET_ADDRESS
        value: UQDn8qu6wduopti68NN9aFjJ0ORN8diPtuUMuR8_7tQG7lai
      - key: PYTHON_VERSION
        value: 3.11.9
